SabalanMedical.UI/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Rotativa.AspNetCore;
using SabalanMedical.UI.Filters.ActionFilters;
using SabalanMedical.UI.Filters.ExceptionFilters;
using SabalanMedical.UI.Filters.ResultFilters.AlwaysRunFilter;
using SabalanMedical.UI.Filters.SkipFilters;
using Serilog;
using ServiceContracts;
using ServiceContracts.DTO.ProductDescriptionDTO;
using ServiceContracts.DTO.ProductImageDTO;
using ServiceContracts.DTO.ProductPropertyDTO;
using ServiceContracts.DTO.ProductsDTO;
 
namespace SabalanMedical.Controllers
{
    [Route("[Controller]")]
    [TypeFilter(typeof(HandleExceptionFilter))]
    [TypeFilter(typeof(ExecutedLogActionFilter))]
    public class ProductsController : Controller
    {
        private readonly IWebHostEnvironment _environement;
        private readonly IProductService _productService;
        private readonly IProductTypeService _productTypeService;
        private readonly IProductImageService _productImageService;
        private readonly IProductDescService _productDescService;
        private readonly IProductPropertyService _productPropertyService;
        private readonly ILogger<ProductsController> _logger;
        private readonly IDiagnosticContext _diagnosticContext;
        public ProductsController(IProductService productService,
            IProductTypeService productTypeService,
            IProductImageService productImageService,
            IProductDescService productDescService,
            IProductPropertyService productPropertyService,
            IWebHostEnvironment environment,
            ILogger<ProductsController> logger, IDiagnosticContext diagnosticContext)
        {
            _productService = productService;
            _productTypeService = productTypeService;
            _productImageService = productImageService;
            _productDescService = productDescService;
            _productPropertyService = productPropertyService;
            _environement = environment;
            _logger = logger;
            _diagnosticContext = diagnosticContext;
        }

        #region Products
        [Route("[action]")]
        [TypeFilter(typeof(TypeListActionFilter))]
        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Index action was executed!");
            List<ProductResponse> productResponses = await _productService.GetAllProducts();
            return View(productResponses);
        }

        [Route("[action]")]
        [HttpGet]
        [TypeFilter(typeof(TypeListActionFilter))]
        public async Task<IActionResult> AddProduct()
        {
            _logger.LogInformation("AddProduct Action get method executed");
            return View();
        }

        [Route("[action]")]
        [HttpPost]
        [TypeFilter(typeof(CheckNullRequestValidationActionFilter), Order = 1)]
        [TypeFilter(typeof(CheckValidationActionFilter), Order = 2)]
        public async Task<IActionResult> AddProduct(ProductAddRequest request)
        {
            _logger.LogInformation("AddProduct action Post method executed");
            await _productService.AddProduct(request);
            _diagnosticContext.Set("Addrequest", request);
            return RedirectToAction("Index", "Products");
        }

        [Route("[action]/{Id}")]
        [HttpGet]
        [TypeFilter(typeof(GuidValidateActionFilter),Order =1)]
        [TypeFilter(typeof(TypeListActionFilter),Order =3)]
        [TypeFilter(typeof(CheckGetProductByIdActionFilter),Order =2)]
        public async Task<IActionResult> EditProduct(Guid Id)
        {
            ProductResponse? response = await _productService.GetProductById(Id);
            return View(response.ToProductUpdateRequest());
        }

        [Route("[action]/{Id}")]//Id: method get and post method has to have the same route
        [HttpPost]
        [TypeFilter(typeof(CheckNullRequestValidationActionFilter))]
        [TypeFilter(typeof(CheckValidationActionFilter))]
        public async Task<IActionResult> EditProduct(ProductUpdateRequest request)
        {
            if (_productService.GetProductById(request.Id) == null)
            {
                _logger.LogError("requset is null");
                return RedirectToAction("index", "Products");
            }
            await _productService.UpdateProduct(request);
            _logger.LogInformation("Redirect to Index method");
            return RedirectToAction("index", "Products");
        }

        [Route("[action]/{Id}")]
        [HttpGet]
        [TypeFilter(typeof(GuidValidateActionFilter))]
        [TypeFilter(typeof(CheckGetProductByIdActionFilter))]
        public async Task<IActionResult> DeleteProduct(Guid Id)
        {
            ProductResponse? response = await _productService.GetProductById(Id);
/*            if (response == null)
            {
                _logger.LogError($"No product was found for id={Id}");
                return RedirectToAction("Index", "Products");
            }*/
            return View(response);
        }

        [Route("[action]/{Id}")]
        [HttpPost]
        [TypeFilter(typeof(CheckNullRequestValidationActionFilter))]
        public async Task<IActionResult> DeleteProduct(ProductResponse request)
        {
            _logger.LogInformation("DeleteProduct action post method executed");
            ProductResponse? response = await _productService.GetProductById(request.Id);
            if (response == null)
            {
                _logger.LogError($"no product was found for id={request.Id} ");
                return RedirectToAction("Index", "Products");
            }
            await _productService.DeleteProduct(request.Id);
            _logger.LogDebug($"{response.ProductNameEn} was deleted");
            return RedirectToAction("Index", "Products");
        }

        [Route("{action}")]
        [HttpPost]
        public async Task<ActionResult> GetFilteredProducts(Guid typeId, string searchBy, string searchKey)
        {
            _logger.LogDebug($"typeId:{typeId}--seachBy={searchBy}--searchKey={searchKey}");
            return ViewComponent("ProductTable", new { typeID = typeId, searchBy = searchBy, searchKey = searchKey });
        }

        [Route("[action]")]
        public async Task<IActionResult> ProductToPDF()
        {
            List<ProductResponse> products = await _productService.GetAllProducts();
            return new ViewAsPdf(products);
        }

        [Route("[action]")]
        public async Task<IActionResult> ProductToCSV()
        {
            MemoryStream memoryStream = await _productService.ProductToCsv();
            return File(memoryStream, "application/octet-stream", "product.csv");
        }
        #endregion

        #region Description
        [Route("[action]/{Id}")]
        [HttpGet]
        [TypeFilter(typeof(GuidValidateActionFilter))]
        public async Task<IActionResult> ProductDescriptions(Guid Id)
        {
            ProductResponse? product = await _productService.GetProductById(Id);
            if (product is null)
            {
                _logger.LogError($"No product was found for id {Id}");
                throw new ArgumentException(nameof(Id));
            }
            return View(product);
        }


        [Route("[action]/{Id}")]//Id=ProductId
        [HttpGet]
        [TypeFilter(typeof(GuidValidateActionFilter))]
        public async Task<IActionResult> AddDescription(Guid Id)
        {
            ProductResponse? Product = await _productService.GetProductById(Id);
            if (Product == null)
            {
                _logger.LogError($"No product was found for productId={Id} ");
                return RedirectToAction("Index");
            }
            ViewBag.Product = Product;
            return View();
        }

        [Route("[action]/{Id}")]//Id=ProductId
        [HttpPost]
        [TypeFilter(typeof(CheckNullRequestValidationActionFilter))]
        public async Task<IActionResult> AddDescription(ProductDescAddRequest request)
        {
            /*            if (request == null)
                        {
                            _logger.LogError("request is null");
                            return RedirectToAction("Index");//redirectToAction Error
                        }*/
            if (!ModelState.IsValid)
            {
                _logger.LogError("validation for request failed");
                ProductResponse? Product = await _productService.GetProductById(request.ProductID);
                ViewBag.Product = Product;
                return View();
            }
            await _productDescService.AddProductDesc(request);
            return RedirectToAction("ProductDescriptions", new { Id = request.ProductID });
        }


        [Route("[action]/Id")]//Id=DescriptionId
        [HttpGet]
        [TypeFilter(typeof(GuidValidateActionFilter))]
        public async Task<IActionResult> DeleteDescription(Guid ID)
        {
            ProductDescResponse? desc = await _productDescService.GetProductDescByDescID(ID);
            if (desc == null)
            {
                _logger.LogError($"No desc was found for descId={ID}");
                return RedirectToAction("Index");
            }
            return View(desc);
        }

        [Route("[action]/Id")]//Id=DescriptionId
        [HttpPost]
        [TypeFilter(typeof(CheckNullRequestValidationActionFilter))]
        public IActionResult DeleteDescription(ProductDescResponse request)
        {
            if (_productDescService.GetProductDescByDescID(request.Id) == null)
            {
                _logger.LogError("desc is null or not fond in database");
                return RedirectToAction("Index");
            }
            _productDescService.DeleteProductDesc(request.Id);
            _logger.LogDebug($"description with id={request.Id} was deleted");
            return RedirectToAction("ProductDescriptions", new { Id = request.ProductID });
        }

SabalanMedical.UI/ViewComponents/ProductTableViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ServiceContracts;
using ServiceContracts.DTO.ProductsDTO;

namespace SabalanMedical.UI.ViewComponents
{
    public class ProductTableViewComponent : ViewComponent
    {
        private readonly IProductService _productService;
        public ProductTableViewComponent(IProductService productService)
        {
            _productService = productService;
        }
        public async Task<IViewComponentResult> InvokeAsync(Guid typeID, string searchBy, string searchKey)
        {
            List<ProductResponse> allProducts = new List<ProductResponse>();
            if (typeID == Guid.Empty)
            {
                allProducts = await _productService.GetFilteredProduct(searchBy, searchKey);
            }
            else
            {
                allProducts = await _productService.GetFilteredProduct(typeID, searchBy, searchKey);
            }
            return View(allProducts);
        }
    }
}

SabalanMedical.UI/Views/Products/AddDescription.cshtml
@model ProductDescAddRequest
@{
    ProductResponse product = ViewBag.Product;
}
<div class="w-50">
    <form asp-controller="Products" asp-action="AddDescription" method="post">
        @*Product Name*@
        <div class="mb-3 row">
            <label id="ProductName" class="col-sm-2 col-form-label">نام محصول</label>
            <div class="col-sm-10">
                <h3 class="form-control" asp-for="DescTitle">@product.ProductNameFr </h3>
            </div>
        </div>
        @*ProductId*@
        <div class="mb-3 row">
            <input type="hidden" class="form-control" asp-for="ProductID" value="@product.Id">
        </div>
        @*Title*@
        <div class="mb-3 row">
            <label asp-for="DescTitle" class="col-sm-2 col-form-label">عنوان</label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="DescTitle">
                <span asp-validation-for="DescTitle" class="text-red"></span>
            </div>
        </div>
        @*Description*@
        <div class="mb-3 row">
            <label asp-for="Description" class="col-sm-2 col-form-label">توضیح</label>
            <div class="col-sm-10">
                <textarea class="form-control" asp-for="Description"></textarea>
                <span asp-validation-for="Description" class="text-red"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Create</button>
        <div asp-validation-summary="All"></div>

        <div>
            @if (ViewBag.Errors != null)
            {
                @foreach (string error in ViewBag.Errors)
                {
                    <div class="alert alert-danger" role="alert">
                        @error
                    </div>
                }
            }
        </div>
    </form>
</div>

@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" asp-fallback-test="window.JQuery" asp-fallback-src="~/js/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js" asp-fallback-test="window.JQuery.validator" asp-fallback-src="~/js/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" asp-fallback-test="window.jquery.validate.unobtrusive" asp-fallback-src="~/js/jquery.validate.unobtrusive.min.js"></script>
}

SabalanMedical.UI/Views/Products/AddProduct.cshtml
@model ProductAddRequest
<div class="w-50">
    <form asp-controller="Products" asp-action="AddProduct" method="post">
        @*ProductType*@
        <div class="mb-3 row">
            <label asp-for="TypeId" class="col-sm-2 col-form-label">نوع محصول</label>
            <select asp-for="TypeId" asp-items="@ViewBag.TypeList" class="form-select form-select-sm" aria-label=".form-select-sm example">
                <option class="text-center" selected>----------نوع محصول را انتخاب کنید-----------</option>
            </select>
            <span asp-validation-for="TypeId"></span>
        </div>
        @*ProductNameEN*@
        <div class="mb-3 row">
            <label asp-for="ProductNameEn" class="col-sm-2 col-form-label">نام محصول به انگلیسی</label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="ProductNameEn">
                <span asp-validation-for="ProductNameEn"></span>
            </div>
        </div>

        @*ProductNameFr*@
        <div class="mb-3 row">
            <label asp-for="ProductNameFr" class="col-sm-2 col-form-label">نام محصول به فارسی</label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="ProductNameFr">
                <span asp-validation-for="ProductNameFr" class="text-red"></span>
            </div>
        </div>
        @*ProductisHotsale*@
        <div class="form-check">
            <input class="form-check-input" value="true" asp-for="isHotSale">
            <label class="form-check-label" asp-for="isHotSale">
                پرفروش
            </label>
        </div>
        @*ProductisManufactored*@
        <div class="form-check">
            <input class="form-check-input" value="true" asp-for="isManufactured">
            <label class="form-check-label" asp-for="isManufactured">
                تولید شرکت
            </label>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
        <div asp-validation-summary="All"></div>
        <div>
            @if (ViewBag.Errors != null)
            {
                @foreach (string error in ViewBag.Errors)
                {
                    <div class="alert alert-danger" role="alert">
                        @error
                    </div>
                }
            }
        </div>
    </form>
</div>

@section scripts{
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" asp-fallback-test="window.JQuery" asp-fallback-src="~/js/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js" asp-fallback-test="window.JQuery.validator" asp-fallback-src="~/js/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" asp-fallback-test="window.jquery.validate.unobtrusive" asp-fallback-src="~/js/jquery.validate.unobtrusive.min.js"></script>
}

SabalanMedical.UI/Views/Products/AddProperty.cshtml
@model ProductPropertyAddRequest
@{
    ProductResponse product = ViewBag.Product;
}
<div class="w-50">
    <form asp-controller="Products" asp-action="AddDescription" method="post">
        @*Product Name*@
        <div class="mb-3 row">
            <label id="ProductName" class="col-sm-2 col-form-label">نام محصول</label>
            <div class="col-sm-10">
                <h3 class="form-control" asp-for="DescTitle">@product.ProductNameFr </h3>
            </div>
        </div>
        @*ProductId*@
        <div class="mb-3 row">
            <input type="hidden" class="form-control" asp-for="ProductID" value="@product.Id">
        </div>
        @*Title*@
        <div class="mb-3 row">
            <label asp-for="PropertyTitle" class="col-sm-2 col-form-label">عنوان</label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="PropertyTitle">
                <span asp-validation-for="PropertyTitle" class="text-red"></span>
            </div>
        </div>
        @*Description*@
        <div class="mb-3 row">
            <label asp-for="PropertyDetail" class="col-sm-2 col-form-label">مشخصات</label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="PropertyDetail">
                <span asp-validation-for="PropertyDetail" class="text-red"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Create</button>
        <div asp-validation-summary="All"></div>

        <div>
            @if (ViewBag.Errors != null)
            {
                @foreach (string error in ViewBag.Errors)
                {
                    <div class="alert alert-danger" role="alert">
                        @error
                    </div>
                }
            }
        </div>
    </form>
</div>

@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" asp-fallback-test="window.JQuery" asp-fallback-src="~/js/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js" asp-fallback-test="window.JQuery.validator" asp-fallback-src="~/js/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" asp-fallback-test="window.jquery.validate.unobtrusive" asp-fallback-src="~/js/jquery.validate.unobtrusive.min.js"></script>
}

SabalanMedical.UI/Views/Products/DeleteDescription.cshtml
@model ProductDescResponse
<div class="container align-content-center">
    <h3>Are you sure to Delete <span class="text">@Model.DescTitle</span></h3>
    <p>@Model.Description</p>

    <form asp-controller="Products" asp-action="DeleteDescription" method="post">

        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="ProductID" />
        <div>
            <button type="submit" class="btn btn-primary">
                <a asp-controller="Products" asp-action="ProductDescriptions" asp-route-Id="@Model.ProductID">Cancell</a>
            </button>

            <button type="submit" class="btn btn-danger">Confirm</button>
        </div>
    </form>
</div>

SabalanMedical.UI/Views/Products/DeleteProduct.cshtml
@model ProductResponse
<div class="container align-content-center">
    <h3>Are you sure to Delete @Model.ProductNameEn</h3>
    @if (Model.productImgs!= null && Model.productImgs.Count!=0)
    {
        <img src="~/images/products/@Model.productImgs.FirstOrDefault().ImageUrl" class="card-img-top" alt="..." style="width: 100%;height: 20rem" />
    }
    else
    {
        <img src="~/images/unKnownImage.jpg" class="card-img-top" alt="..." style="width: 100%;height: 20rem" />
    }
    <form asp-controller="Products" asp-action="DeleteProduct" method="post">

        <input type="hidden" asp-for="Id" />
        <div>
            <button type="button" class="btn btn-primary">
                <a asp-controller="Products" asp-action="index">Cancell</a>
            </button>

            <button type="submit" class="btn btn-danger">Confirm</button>
        </div>
    </form>
</div>

SabalanMedical.UI/Views/Products/DeleteProperty.cshtml
@model ProductPropertyResponse
<div class="container align-content-center">
    <h3>Are you sure to Delete <span class="text">@Model.PropertyTitle</span></h3>
    <p>@Model.PropertyDetail</p>

    <form asp-controller="Products" asp-action="DeleteProperty" method="post">

        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="ProductID" />
        <div>
            <button type="submit" class="btn btn-primary">
                <a asp-controller="Products" asp-action="ProductProperties" asp-route-Id="@Model.ProductID">Cancell</a>
            </button>

            <button type="submit" class="btn btn-danger">Confirm</button>
        </div>
    </form>
</div>

SabalanMedical.UI/Views/Products/EditDescription.cshtml
@model ProductDescUpdateRequest

<div class="w-50">
    <form asp-controller="Products" asp-action="AddDescription" method="post">
        @*DescriptionId*@
        <div class="mb-3 row">
            <input type="hidden" class="form-control" asp-for="Id">
        </div>
        @*ProductId*@
        <div class="mb-3 row">
            <input type="hidden" class="form-control" asp-for="ProductID">
        </div>
        @*Title*@
        <div class="mb-3 row">
            <label asp-for="DescTitle" class="col-sm-2 col-form-label">عنوان</label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="DescTitle">
                <span asp-validation-for="DescTitle" class="text-red"></span>
            </div>
        </div>
        @*Description*@
        <div class="mb-3 row">
            <label asp-for="Description" class="col-sm-2 col-form-label">توضیح</label>
            <div class="col-sm-10">
                <textarea asp-for="Description" class="form-control" >

                </textarea>
                <span asp-validation-for="Description"  class="text-red"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Create</button>
        <div asp-validation-summary="All"></div>

        <div>
            @if (ViewBag.Errors != null)
            {
                @foreach (string error in ViewBag.Errors)
                {
                    <div class="alert alert-danger" role="alert">
                        @error
                    </div>
                }
            }
        </div>
    </form>
</div>

@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" asp-fallback-test="window.JQuery" asp-fallback-src="~/js/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js" asp-fallback-test="window.JQuery.validator" asp-fallback-src="~/js/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" asp-fallback-test="window.jquery.validate.unobtrusive" asp-fallback-src="~/js/jquery.validate.unobtrusive.min.js"></script>
}

SabalanMedical.UI/Views/Products/EditProduct.cshtml
@model ProductUpdateRequest
<div class="w-50">
    <form asp-controller="Products" asp-action="EditProduct" method="post">

        <input asp-for="Id" type="hidden" />

        @*ProductType*@
        <div class="mb-3 row">
            <label asp-for="TypeId" class="col-sm-2 col-form-label">نوع محصول</label>
            <select asp-for="TypeId" asp-items="@ViewBag.TypeList" class="form-select form-select-sm" aria-label=".form-select-sm example">
                <option class="text-center" selected>----------نوع محصول را انتخاب کنید-----------</option>
            </select>
            <span asp-validation-for="TypeId"></span>
        </div>

        @*ProductNameEN*@
        <div class="mb-3 row">
            <label asp-for="ProductNameEn" class="col-sm-2 col-form-label">نام محصول به انگلیسی</label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="ProductNameEn">
                <span asp-validation-for="ProductNameEn"></span>
            </div>
        </div>

        @*ProductNameFr*@
        <div class="mb-3 row">
            <label asp-for="ProductNameFr" class="col-sm-2 col-form-label">نام محصول به فارسی</label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="ProductNameFr">
                <span asp-validation-for="ProductNameFr" class="text-red"></span>
            </div>
        </div>

        @*ProductUrl*@
        <div class="mb-3 row">
            <label asp-for="ProductUrl" class="col-sm-2 col-form-label">نام محصول به فارسی</label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="ProductUrl">
                <span asp-validation-for="ProductUrl" class="text-red"></span>
            </div>
        </div>
        @*ProductisHotsale*@
        <div class="form-check">
            <input class="form-check-input" value="true" asp-for="isHotSale">
            <label class="form-check-label" asp-for="isHotSale">
                پرفروش
            </label>
        </div>

        @*ProductisManufactored*@
        <div class="form-check">
            <input class="form-check-input" value="true" asp-for="isManufactured">
            <label class="form-check-label" asp-for="isManufactured">
                تولید شرکت
            </label>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
        <div asp-validation-summary="All"></div>
        <div>
            @if (ViewBag.Errors != null)
            {
                @foreach (string error in ViewBag.Errors)
                {
                    <div class="alert alert-danger" role="alert">
                        @error
                    </div>
                }
            }
        </div>
    </form>
</div>

@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" asp-fallback-test="window.JQuery" asp-fallback-src="~/js/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js" asp-fallback-test="window.JQuery.validator" asp-fallback-src="~/js/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" asp-fallback-test="window.jquery.validate.unobtrusive" asp-fallback-src="~/js/jquery.validate.unobtrusive.min.js"></script>
}

SabalanMedical.UI/Views/Products/Index.cshtml
@model List<ProductResponse>
<div class="container">
    <div>
        <a asp-controller="Products" asp-action="ProductToPDF">Convert To PDF</a>
        <a asp-controller="Products" asp-action="ProductToCSV">Convert To CSV</a>
    </div>
    <div class="row">
        <form class="row col-md-3 container col-md-3" method="post">
            <h5>نوع محصول</h5>
            <select id="selectType" asp-items="@ViewBag.TypeList" class="form-select text-center fw-bold" aria-label="Default select example">
                <option class="text-center" selected value="0">----انتخاب نوع محصول----</option>
            </select>
        </form>
    </div>
    <div class="row mt-3">
        <div class="flex-row left-align">
            <a href="~/Products/AddProduct">
                <i class="bi-file-plus fs-3 text-success" id="addProductButton">محصول جدید</i>
            </a>
        </div>
        <table id="tblProducts" class="table-bordered">
            <thead>
                <tr class="search_head_title">
                    <th>جستجو بر اساس نوع</th>
                    <th>جستجو بر اساس نام انگلیسی</th>
                    <th>جستجوی نام به فارسی</th>
                </tr>
                <tr class="search_head_text">
                    <th><div id="searchType" contenteditable="true"></div></th>
                    <th><div id="searchEn" class="border-danger" contenteditable="true"></div></th>
                    <th><div id="searchPr" class="border-danger" contenteditable="true"></div></th>
                </tr>
                <tr>
                    <th>Type of product</th>
                    <th>Name of product</th>
                    <th>نام محصول</th>
                    <th>پرفروش</th>
                    <th>تولید شرکت</th>
                    <th>productUrl</th>
                    <th>حدف</th>
                    <th>ویرایش</th>
                    <th>عکسها</th>
                    <th>توضیحات</th>
                    <th>مشخصات</th>
                </tr>
            </thead>
            <tbody id="productBody">
                @await Component.InvokeAsync("ProductTable")
            </tbody>
        </table>

    </div>
</div>
@section scripts{
    <script src="~/js/Store.js"> </script>
}

SabalanMedical.UI/Views/Products/ProductToPDF.cshtml
@model List<ProductResponse>
@{
    Layout = null;
}
<link rel="stylesheet" href="~/bootstrap-5.1.3-dist/icons-1.7.2/font/bootstrap-icons.css">
<link rel="stylesheet" href="~/css/main.css">
<table id="tblProducts" class="table-bordered">
    <thead>
        <tr>
            <th>Type of product</th>
            <th>Name of product</th>
            <th>نام محصول</th>
            <th>پرفروش</th>
            <th>تولید شرکت</th>
            <th>productUrl</th>
            <th>حدف</th>
            <th>ویرایش</th>
            <th>عکسها</th>
            <th>توضیحات</th>
            <th>مشخصات</th>
        </tr>
    </thead>
    <tbody id="productBody">
        @await Component.InvokeAsync("ProductTable")
    </tbody>
</table>