SabalanMedical.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SabalanMedical.UI.Filters.ActionFilters;
using SabalanMedical.UI.Filters.ResultFilters;
using Serilog;
using ServiceContracts;
using ServiceContracts.DTO.ProductsDTO;

namespace SabalanMedical.Controllers
{
    [TypeFilter(typeof(ExecutedLogActionFilter))]
    [TypeFilter(typeof(TokenResltFilter))]
    public class HomeController : Controller
    {
        private readonly IProductTypeService _productTypeService;
        private readonly IProductService _productService;
        private readonly IProductImageService _productImageService;
        private readonly IProductDescService _productDescService;
        private readonly IProductPropertyService _productPropertyService;
        private readonly ILogger<HomeController> _logger;
        
        public HomeController(IProductTypeService productTypeService,
            IProductService productService,
            IProductImageService productImageService,
            IProductDescService productDescService,
            IProductPropertyService productPropertyService,
            ILogger<HomeController> logger)
        {
            _logger = logger;
            _productTypeService = productTypeService;
            _productService = productService;
            _productImageService = productImageService;
            _productDescService = productDescService;
            _productPropertyService = productPropertyService;
        }

        [Route("/")]
        [Route("[action]")]
        public async Task<IActionResult> Index()
        {
            List<ProductResponse> allProducts = await _productService.GetAllProducts();
            ViewBag.Title = "صفحه اول";
            return View(allProducts);
        }
        [Route("[action]")]
        public IActionResult Contact()
        {
            ViewBag.Title = "تماس با ما";
            return View();
        }
        [Route("[action]")]
        public IActionResult About()
        {
            ViewBag.Title = "درباره ما";
            return View();
        }

        [Route("[action]")]
        public IActionResult Cooperation()
        {
            ViewBag.Title = "همکاری با ما";
            return View();
        }

        [Route("[action]")]
        public async Task<IActionResult> OurProducts()
        {
            List<ProductResponse> allProducts = await _productService.GetAllProducts();
            IEnumerable<ProductResponse> allManufacturedProducts = allProducts.Where(t => t.isManufactured == true);
            _logger.LogDebug($"{allManufacturedProducts.Count()} was founde as Manufactured products");
            ViewBag.Title = "تولیدات ما";
            return View(allManufacturedProducts);
        }

        [Route("[action]/{productUrl}")]
        public async Task<IActionResult> OurProductDetails(string productUrl)
        {
            _logger.LogDebug($"Try to finde info for Product Url: {productUrl}");
            ProductResponse? Product = await _productService.GetProductByProductUrl(productUrl);
            if (Product == null)
            {
                _logger.LogError($"No product was fond for {productUrl}");
                throw new ArgumentNullException(nameof(productUrl));
            }
            return View(Product);
        }
        [Route("[action]")]
        [HttpGet]
        public async Task<IActionResult> Store()
        {
            List<ProductResponse> allProducts = await _productService.GetAllProducts();
            _logger.LogDebug($"{allProducts.Count()} products was found");
            return View(allProducts.OrderBy(t => t.TypeId));
        }
        [Route("[action]/{productUrl}")]
        [HttpGet]
        public async Task<IActionResult> Product(string productUrl)
        {
            _logger.LogDebug($"product url is :{productUrl}");
            if (productUrl == null)
            {
                _logger.LogError("Url is null!");
                throw new ArgumentNullException(nameof(productUrl));
            }
            ProductResponse? product = await _productService.GetProductByProductUrl(productUrl);
            if (product == null)
            {
                _logger.LogError($"No product was found for url: {productUrl}");
                throw new ArgumentException(nameof(productUrl));
            }
            _logger.LogDebug($"product for the url: {productUrl} is  :{product.ProductNameEn}");
            return View(product);
        }
        [Route("[action]/{typeEn}")]
        public async Task<IActionResult> ProductTypes(string? typeEn)
        {
            _logger.LogDebug($"Type is: {typeEn}");
            if (typeEn is null)
            {
                _logger.LogError($"No Id found for typeEn :{typeEn}");
                throw new ArgumentNullException(nameof(typeEn));
            }
            List<ProductResponse>? products = await _productService.GetProductByTypeName(typeEn);
            if (products is null)
            {
                _logger.LogError($"No prodcts was found for typeEn :{typeEn}");
                throw new ArgumentNullException(nameof(typeEn));
            }
            _logger.LogDebug($"{products.Count} products was found for type of {typeEn}");
            ViewBag.Title = typeEn;
            ViewBag.Type = typeEn;
            return View(products);
        }
    }
}

SabalanMedical.UI/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Rotativa.AspNetCore;
using SabalanMedical.UI.Filters.ActionFilters;
using SabalanMedical.UI.Filters.ExceptionFilters;
using SabalanMedical.UI.Filters.ResultFilters.AlwaysRunFilter;
using SabalanMedical.UI.Filters.SkipFilters;
using Serilog;
using ServiceContracts;
using ServiceContracts.DTO.ProductDescriptionDTO;
using ServiceContracts.DTO.ProductImageDTO;
using ServiceContracts.DTO.ProductPropertyDTO;
using ServiceContracts.DTO.ProductsDTO;
 
namespace SabalanMedical.Controllers
{
    [Route("[Controller]")]
    [TypeFilter(typeof(HandleExceptionFilter))]
    [TypeFilter(typeof(ExecutedLogActionFilter))]
    public class ProductsController : Controller
    {
        private readonly IWebHostEnvironment _environement;
        private readonly IProductService _productService;
        private readonly IProductTypeService _productTypeService;
        private readonly IProductImageService _productImageService;
        private readonly IProductDescService _productDescService;
        private readonly IProductPropertyService _productPropertyService;
        private readonly ILogger<ProductsController> _logger;
        private readonly IDiagnosticContext _diagnosticContext;
        public ProductsController(IProductService productService,
            IProductTypeService productTypeService,
            IProductImageService productImageService,
            IProductDescService productDescService,
            IProductPropertyService productPropertyService,
            IWebHostEnvironment environment,
            ILogger<ProductsController> logger, IDiagnosticContext diagnosticContext)
        {
            _productService = productService;
            _productTypeService = productTypeService;
            _productImageService = productImageService;
            _productDescService = productDescService;
            _productPropertyService = productPropertyService;
            _environement = environment;
            _logger = logger;
            _diagnosticContext = diagnosticContext;
        }

        #region Products
        [Route("[action]")]
        [TypeFilter(typeof(TypeListActionFilter))]
        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Index action was executed!");
            List<ProductResponse> productResponses = await _productService.GetAllProducts();
            return View(productResponses);
        }

        [Route("[action]")]
        [HttpGet]
        [TypeFilter(typeof(TypeListActionFilter))]
        public async Task<IActionResult> AddProduct()
        {
            _logger.LogInformation("AddProduct Action get method executed");
            return View();
        }

        [Route("[action]")]
        [HttpPost]
        [TypeFilter(typeof(CheckNullRequestValidationActionFilter), Order = 1)]
        [TypeFilter(typeof(CheckValidationActionFilter), Order = 2)]
        public async Task<IActionResult> AddProduct(ProductAddRequest request)
        {
            _logger.LogInformation("AddProduct action Post method executed");
            await _productService.AddProduct(request);
            _diagnosticContext.Set("Addrequest", request);
            return RedirectToAction("Index", "Products");
        }

        [Route("[action]/{Id}")]
        [HttpGet]
        [TypeFilter(typeof(GuidValidateActionFilter),Order =1)]
        [TypeFilter(typeof(TypeListActionFilter),Order =3)]
        [TypeFilter(typeof(CheckGetProductByIdActionFilter),Order =2)]
        public async Task<IActionResult> EditProduct(Guid Id)
        {
            ProductResponse? response = await _productService.GetProductById(Id);
            return View(response.ToProductUpdateRequest());
        }

        [Route("[action]/{Id}")]//Id: method get and post method has to have the same route
        [HttpPost]
        [TypeFilter(typeof(CheckNullRequestValidationActionFilter))]
        [TypeFilter(typeof(CheckValidationActionFilter))]
        public async Task<IActionResult> EditProduct(ProductUpdateRequest request)
        {
            if (_productService.GetProductById(request.Id) == null)
            {
                _logger.LogError("requset is null");
                return RedirectToAction("index", "Products");
            }
            await _productService.UpdateProduct(request);
            _logger.LogInformation("Redirect to Index method");
            return RedirectToAction("index", "Products");
        }

        [Route("[action]/{Id}")]
        [HttpGet]
        [TypeFilter(typeof(GuidValidateActionFilter))]
        [TypeFilter(typeof(CheckGetProductByIdActionFilter))]
        public async Task<IActionResult> DeleteProduct(Guid Id)
        {
            ProductResponse? response = await _productService.GetProductById(Id);
/*            if (response == null)
            {
                _logger.LogError($"No product was found for id={Id}");
                return RedirectToAction("Index", "Products");
            }*/
            return View(response);
        }

        [Route("[action]/{Id}")]
        [HttpPost]
        [TypeFilter(typeof(CheckNullRequestValidationActionFilter))]
        public async Task<IActionResult> DeleteProduct(ProductResponse request)
        {
            _logger.LogInformation("DeleteProduct action post method executed");
            ProductResponse? response = await _productService.GetProductById(request.Id);
            if (response == null)
            {
                _logger.LogError($"no product was found for id={request.Id} ");
                return RedirectToAction("Index", "Products");
            }
            await _productService.DeleteProduct(request.Id);
            _logger.LogDebug($"{response.ProductNameEn} was deleted");
            return RedirectToAction("Index", "Products");
        }

        [Route("{action}")]
        [HttpPost]
        public async Task<ActionResult> GetFilteredProducts(Guid typeId, string searchBy, string searchKey)
        {
            _logger.LogDebug($"typeId:{typeId}--seachBy={searchBy}--searchKey={searchKey}");
            return ViewComponent("ProductTable", new { typeID = typeId, searchBy = searchBy, searchKey = searchKey });
        }

        [Route("[action]")]
        public async Task<IActionResult> ProductToPDF()
        {
            List<ProductResponse> products = await _productService.GetAllProducts();
            return new ViewAsPdf(products);
        }

        [Route("[action]")]
        public async Task<IActionResult> ProductToCSV()
        {
            MemoryStream memoryStream = await _productService.ProductToCsv();
            return File(memoryStream, "application/octet-stream", "product.csv");
        }
        #endregion

        #region Description
        [Route("[action]/{Id}")]
        [HttpGet]
        [TypeFilter(typeof(GuidValidateActionFilter))]
        public async Task<IActionResult> ProductDescriptions(Guid Id)
        {
            ProductResponse? product = await _productService.GetProductById(Id);
            if (product is null)
            {
                _logger.LogError($"No product was found for id {Id}");
                throw new ArgumentException(nameof(Id));
            }
            return View(product);
        }


        [Route("[action]/{Id}")]//Id=ProductId
        [HttpGet]
        [TypeFilter(typeof(GuidValidateActionFilter))]
        public async Task<IActionResult> AddDescription(Guid Id)
        {
            ProductResponse? Product = await _productService.GetProductById(Id);
            if (Product == null)
            {
                _logger.LogError($"No product was found for productId={Id} ");
                return RedirectToAction("Index");
            }
            ViewBag.Product = Product;
            return View();
        }

        [Route("[action]/{Id}")]//Id=ProductId
        [HttpPost]
        [TypeFilter(typeof(CheckNullRequestValidationActionFilter))]
        public async Task<IActionResult> AddDescription(ProductDescAddRequest request)
        {
            /*            if (request == null)
                        {
                            _logger.LogError("request is null");
                            return RedirectToAction("Index");//redirectToAction Error
                        }*/
            if (!ModelState.IsValid)
            {
                _logger.LogError("validation for request failed");
                ProductResponse? Product = await _productService.GetProductById(request.ProductID);
                ViewBag.Product = Product;
                return View();
            }
            await _productDescService.AddProductDesc(request);
            return RedirectToAction("ProductDescriptions", new { Id = request.ProductID });
        }


        [Route("[action]/Id")]//Id=DescriptionId
        [HttpGet]
        [TypeFilter(typeof(GuidValidateActionFilter))]
        public async Task<IActionResult> DeleteDescription(Guid ID)
        {
            ProductDescResponse? desc = await _productDescService.GetProductDescByDescID(ID);
            if (desc == null)
            {
                _logger.LogError($"No desc was found for descId={ID}");
                return RedirectToAction("Index");
            }
            return View(desc);
        }

        [Route("[action]/Id")]//Id=DescriptionId
        [HttpPost]
        [TypeFilter(typeof(CheckNullRequestValidationActionFilter))]
        public IActionResult DeleteDescription(ProductDescResponse request)
        {
            if (_productDescService.GetProductDescByDescID(request.Id) == null)
            {
                _logger.LogError("desc is null or not fond in database");
                return RedirectToAction("Index");
            }
            _productDescService.DeleteProductDesc(request.Id);
            _logger.LogDebug($"description with id={request.Id} was deleted");
            return RedirectToAction("ProductDescriptions", new { Id = request.ProductID });
        }

SabalanMedical.UI/ViewComponents/ManufacturedViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ServiceContracts;
using ServiceContracts.DTO.ProductsDTO;
using Services;

namespace SabalanMedical.UI.ViewComponents
{
    public class ManufacturedViewComponent : ViewComponent
    {
        private readonly IProductService _productService;
        public ManufacturedViewComponent(IProductService productService)
        {
            _productService = productService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<ProductResponse> allProducts = await _productService.GetAllProducts();

           List<ProductResponse> manufacturedProducts =allProducts.Where(t => t.isManufactured == true).ToList();
            return View(manufacturedProducts);//shared/Components/Manufactured/default.cshtml
        }
    }
}

SabalanMedical.UI/Views/Home/Index.cshtml
@model List<ProductResponse>
<section>
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active " aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="images/banners/baner%20(3).jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>انواع کارتریج </h5>
                    <p>وارد کننده اصلی انواع کارتریج اشلون</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="images/banners/baner%20(2).jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>واردات مستقیم محصولات لاپاراسکوپی</h5>
                    <p>خرید مستقیم محصولات لاپاراسکوپی از وارد کننده اصلی و حذف واسطه</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="images/banners/baner%20(1).jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>محصولات بیهوشی تنفسی</h5>
                    <p>تولید کننده و وارد کننده انواع محصولات بیهوشی تنفسی و اتاق عمل</p>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</section>
<section>
    <div class="container">
        <div class="row ourOptions d-flex justify-content-around">
            <div class="col">
                <i class="bi-house-fill"></i>
                <p>خرید بدون واسطه</p>
            </div>
            <div class="col">
                <i class="bi-truck"></i>
                <p>ارسال به تمام نقاط کشور</p>
            </div>
            <div class="col">
                <i class="bi-speedometer2"></i>
                <p>ارسال سریع</p>
            </div>
            <div class="col">
                <i class="bi-graph-down"></i>
                <p>قیمت رقابتی</p>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="container-xxl mb-5 mt-5 advSection">
        <div class="row justify-content-center">
            <section class="col-sm-7">
                <div class="card" style="min-width: 18rem;height: 100%">
                    <div class="cardImages" style="height: 100%">
                        <img src="images/adv/adv%20(2).jpg" class="card-img-top" alt="...">
                    </div>
                    <div class="card-body">
                        <h5 class="card-text text-center">واردات مستقیم اسپیلنت بینی در انواع رنگها و مدلها از چین</h5>
                    </div>
                </div>
            </section>
            <section class="col-sm-5" style="min-width: 350px">
                <div class="row row-cols-1 row-cols-md-2 g-4">
                    <div class="col">
                        <div class="card">
                            <div class="cardImages">
                                <img src="images/adv/adv (1).jpg" class="card-img-top" alt="...">
                            </div>
                            <div class="card-body">
                                <p class="card-text">نخستین تولید کننده تامپون بینی در ایران </p>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card">
                            <div class="cardImages">
                                <img src="images/adv/adv (3).jpg" class="card-img-top" alt="...">
                            </div>
                            <div class="card-body">
                                <p class="card-text">واردات مستقیم محصولات لاپاراسکوپی</p>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card ">
                            <div class="cardImages">
                                <img src="images/adv/adv (4).jpg" class="card-img-top" alt="...">
                            </div>
                            <div class="card-body">
                                <p class="card-text">تولید کننده فیلتر آنتی باکاریال</p>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card">
                            <div class="cardImages">
                                <img src="images/adv/adv (5).jpg" class="card-img-top" alt="...">
                            </div>
                            <div class="card-body">
                                <p class="card-text">تولید کننده فیلتر HME </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mt-5">
                    <a class="main-page-more-products" asp-action="OurProducts" asp-controller="Home">بیشتر</a>
                </div>
            </section>
        </div>
    </div>
</section>
<section>
    <div class="container">
        <div class="d-flex justify-content-lg-center flex-column mt-4 mb-4 text-lg-center fs-1">
            <span class="text-center">محصولات پرفروش</span>
            <i class="bi bi-activity text-danger text-center"></i>
        </div>
    </div>
    <div class="container">
        <div class="row row-cols-1 row-cols-md-4 g-4">
            @{
                foreach (ProductResponse product in Model.Where(t=>t.isHotSale==true))
                {
                    <div class="col">
                        <div class="card myCard">
                            <a asp-action="Product" asp-controller="Home" asp-route-productUrl="@product.ProductUrl">
                                <div class="cardImages">
                                    @if (product.productImgs?.Count!=0)
                                    {
                                        <img src="~/images/products/@product.productImgs?.FirstOrDefault().ImageUrl" class="card-img-top " alt="@product.productType.TypeNameFr" style="width: 100%;height: 20rem">
                                    }else{
                                        <img src="~/images/unKnownImage.jpg" class="card-img-top " alt="@product.productType.TypeNameFr" style="width: 100%;height: 20rem">
                                    }
                                </div>
                            </a>
                            <div class="card-body">

                                <p class="card-text text-center">@product.productType.TypeNameEN</p>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</section>
<section>
    <div class="card  text-white mt-5 mb-5" style="background-color: darkblue">
        <img src="images/banners/baner%20(1).jpg" class="card-img" alt="..." style="opacity: .3;height: 300px">
        <div class="card-img-overlay d-flex flex-column">
            <h3 class="card-title text-center fw-bold mb-4 mt-5">
                با ما بیشتر آشنا شوید
            </h3>
            <p class="text-center text-white text-wrap">
                خدمات پس از فروش و 24 ساعته بصورت آنلاین<br>
                به شما کمک میکنیم در کمترین زمان ممکن به آنچه میخواهید برسید
            </p>
            <h5 class="card-title text-center fs-5 mt-4 fw-bold">
                <a CLASS="text-white contactUS" HREF="contact"> تماس با ما <i class="bi-arrow-right"></i></a>
            </h5>
        </div>
    </div>
</section>
<section>
    <div class="container">
        <div class="d-flex justify-content-lg-center flex-column mt-4 mb-4 text-lg-center fs-1">
            <span class="text-center">دسته بندی محصولات</span>
            <i class="bi bi-activity text-danger text-center"></i>
        </div>
        <div class="row row-cols-1 row-cols-md-4 g-4">
            @{
                foreach (ProductResponse item in Model.DistinctBy(t => t.TypeId))
                {
                    <div class="col">
                        <div class="myCard card">
                            <a asp-action="ProductTypes" asp-controller="Home" asp-route-typeEn="@item.productType.TypeNameEN">
                                <div class="cardImages">
                                @if(item.productImgs.Count!=0){
                                    <img src="images/products/@item.productImgs.FirstOrDefault().ImageUrl" class="card-img-top " alt="@item.productType.TypeNameFr" style="width: 100%;height: 20rem">
                                    }
                                </div>
                            </a>
                            <div class="card-body">
                                <p class="card-text text-center">@item.productType.TypeNameFr</p>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</section>
@await Component.InvokeAsync("Manufactured")

SabalanMedical.UI/Views/Home/Store.cshtml
@model IEnumerable<ProductResponse>
<div class="card bg-dark text-white mb-3">
    <img src="~/images/banners/baner%20(1).jpg" class="card-img" alt="..." style="opacity: .6;height: 300px">
    <div class="card-img-overlay d-flex justify-content-center align-items-center">
        <div class="card-title text-center fs-5 fw-bold d-flex justify-content-between ">
            <a CLASS="text-white fs-4" asp-controller="Home" asp-action="/">صفحه اصلی</a>
            <i class="bi-chevron-double-left fs-3"></i>
            <a CLASS="text-white fs-4">فروشگاه</a>
        </div>
    </div>
</div>
<div class="container-xxl">
    <div class="row mt-3 pt-2">
        <section class="col-lg-3 ">
            <form class="form-control pt-3 pb-3" method="get">
                <div class="d-flex align-items-center mb-4">
                    <i class="bi-book fs-2 text-danger ms-2"></i>
                    <h5 class="text-muted">گروه کالا</h5>
                </div>
                <ul>
                    @foreach (ProductResponse type in Model.DistinctBy(t=>t.TypeId))
                    {
                        <div class="form-check form-switch mb-3">
                            <input class="form-check-input" name="@type.productType.TypeNameEN" checked type="checkbox" role="switch"
                                   id="@type.TypeId" value="@type.productType.TypeNameFr">
                            <label class="form-check-label" for="@type.TypeId">@type.productType.TypeNameFr</label>
                        </div>
                    }
                </ul>
                <form asp-action="">
                </form>
                <input class="btn btn-outline-danger w-100" type="submit" value="جستجو">
            </form>
            <div class="mt-5 mb-5">
                <h5 class="mb-3">پرفروشترین ها</h5>

                @foreach (ProductResponse item in Model.Where(t => t.isHotSale == true))
                {
                    <div class="card mb-3 store-hot-sale-card" style="width: 100%;height: 100px">
                        <div class="row g-0">
                            <div class="col-md-4" style="height: 100px">
                                <img src="~/images/products/@item.productImgs?.FirstOrDefault()?.ImageUrl" class="img-fluid rounded-start" alt="@item.ProductNameFr" style="width: 150px;height: 100%">
                            </div>
                            <div class="col-md-8 ">
                                <div class="card-body store-hot-sale">
                                    <h6 class="card-title mb-3">@item.ProductNameFr</h6>
                                    <a class="card-text text-center" asp-controller="Home" asp-action="Product" asp-route-productUrl="@item.ProductUrl"><i class="bi-cart-dash"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </section>
        <section class="col-lg-9  p-1">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                @foreach (ProductResponse item in Model)
                {
                    <div class="col">
                        <div class="card">
                            <div class="shop-image">
                                <a asp-controller="Home" asp-action="Product" asp-route-productUrl="@item.ProductUrl">خرید کالا</a>
                                <img src="~/images/products/@item.productImgs?.FirstOrDefault()?.ImageUrl" class="card-img-top" alt="@item.ProductNameFr" style="width: 100%;height: 300px">
                            </div>
                            <div class="card-body">
                                <ul class="d-flex justify-content-around p-0">
                                    <li><h6 class="card-title text-danger">@item.ProductNameFr</h6></li>
                                    <li><p class="card-title fs-6">@item.ProductNameEn</p></li>
                                </ul>
                                <p class="card-text me-2 shop-call"><i class="bi-telephone text-danger ms-2 "></i>تماس بگیرید  </p>
                                <p class="card-text text-muted fs-6"><small class="text-muted">گروه : </small>@item.productType.TypeNameFr</p>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </section>
    </div>
</div>
@await Component.InvokeAsync("Manufactured")

SabalanMedical.UI/Views/Home/TestSelenium.cshtml
<h1>selenium</h1>